### ISSUE TITLE
Pressing F7 or Shift+F7 throw an exception.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/F7History#1]
```
An exception occurred in custom key handler, see $error for more information: The term 'ocgv_history' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by tig** [comment]
You're running `F7History.ps1` from your $profile script, right?

I just tested doing that instead of pasting the code in directly to $profile and I get the error too. 

Odd.

**Comment by tig** [comment]
Prefix `F7History.ps1` with `.`:

```powershell
. ~/s/F7History/F7History.ps1

function killp { Get-Process | Out-ConsoleGridView -OutputMode Single -Filter $args[0] | Stop-Process -Id {$_.Id} }
```

That causes PS to *include* the script, vs. running it.

**Comment by BDisp** [comment]
> You're running `F7History.ps1` from your $profile script, right?
> 
Sorry, what do you meaning by my $profile script? How can I create it?

> I just tested doing that instead of pasting the code in directly to $profile and I get the error too.
> 
I suspected that something is wrong anyway because I run successfully the code on the Graphical issue.

> Odd.
Really is.

**Comment by tig** [comment]
> > You're running `F7History.ps1` from your $profile script, right?
> 
> Sorry, what do you meaning by my $profile script? How can I create it?

```powershell
PS> code $profile
```

**Comment by tig** [comment]
I fixed the README to make this more clear.
