### ISSUE TITLE
"ls | ocgv" command on the F7History folder outputs escape sequences.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/F7History#14]
![imagem](https://github.com/gui-cs/F7History/assets/13117724/b5c8e155-c5c7-4871-bbd4-453388ea4ed4)

![imagem](https://github.com/gui-cs/F7History/assets/13117724/cce04fab-8333-4c15-a4e4-44f383f7130a)

![imagem](https://github.com/gui-cs/F7History/assets/13117724/b7a49f88-2cc8-4c5e-8dd2-528658b65847)

**Comment by tig** [comment]
That's an anicent verison of OCGV. Note columns aren't aligned.

**Comment by BDisp** [comment]
I see. Do you think is better close this?

**Comment by tig** [comment]
Remove all old verisons of OGCV/ConsoleGuiTools. Then re-install using `Install-Module`. Does that fix it?

**Comment by BDisp** [comment]
Yes it did, thanks.

![imagem](https://github.com/gui-cs/F7History/assets/13117724/c190d5d4-bb67-42c0-bebc-29963fa8762b)

**Comment by tig** [comment]
Install oh-my-posh and terminal-icons and you get this:

<img width="638" alt="image" src="https://github.com/gui-cs/F7History/assets/585482/0323807d-4215-4568-83b2-b24600e6deb0">

**Comment by BDisp** [comment]
@tig I already installed but the icons doesn't appear.

![imagem](https://github.com/gui-cs/F7History/assets/13117724/548f6887-6523-4812-a772-6d04a0656530)

**Comment by BDisp** [comment]
Done, I forgot to add them to my profile, but your icons are bigger than mine. What font do you are using?

![imagem](https://github.com/gui-cs/F7History/assets/13117724/692a97b7-d6da-4e32-8221-77830bd07f9e)

**Comment by tig** [comment]
<img width="190" alt="image" src="https://github.com/gui-cs/F7History/assets/585482/3883588e-79eb-4110-b92b-66568fe9d82c">

**Comment by BDisp** [comment]
> <img alt="image" width="190" src="https://user-images.githubusercontent.com/585482/257068994-3883588e-79eb-4110-b92b-66568fe9d82c.png">

Ops I can't find that font, where did you download it?

**Comment by tig** [comment]
https://www.nerdfonts.com/
