### ISSUE TITLE
Dependent modules are not automatically getting installed

### ISSUE THREAD

**Issue by tig** [gui-cs/F7History#18]
WIth v1.3 when I was using `RequiredModules.RequiredModules` if a user did `Install-Module F7History` the dependent module `Microsoft.PowerTools.ConsoleGuiTools` was installed. PS Gallery showed:

![image](https://github.com/gui-cs/F7History/assets/585482/e36b415d-5f7f-4c49-b121-af6ec2d64086)

Now, with v1.4.x this is not working.  Users get:

```ps1
> install-module f7history -Repository PSGallery
WARNING: The externally managed, dependent module 'Microsoft.PowerShell.ConsoleGuiTools' is not installed on this computer. To use the current module 'F7History', ensure that its dependent module 'Microsoft.PowerShell.ConsoleGuiTools' is installed.
```

PS Gallery shows:

![image](https://github.com/gui-cs/F7History/assets/585482/ddcb1d40-755b-40c1-b313-a516535ae233)

@RH-TLagrone, is there some way to make `RequiredModules` both not require a specific version AND auto-install dependent modules?

```ps1
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'PSReadline'; ModuleVersion = '2.1'; }, 
               @{ModuleName = 'Microsoft.PowerShell.ConsoleGuiTools'; ModuleVersion = '0.7.6.0'; })
```

**Comment by RH-TLagrone** [comment]
Yes. Basically:

Change this...

```powershell
RequiredModules = @(
  @{ModuleName='PSReadLine'; ModuleVerison='2.1'}
  @{ModuleName='Microsoft.PowerShell.ConsoleGuiTools'; ModuleVersion='0.7.6.0'}
)
```

...into this:

```powershell
RequiredModules = @(
  'PSReadLine'
  'Microsoft.PowerShell.ConsoleGuiTools'
)
```

...also, you probably want to wholly remove the `PrivateData.PSData.ExternalModuleDependencies` field since it has incompatible semantics with the `RequiredModules` field. _(I'm not sure if actually affects publication/installation, but better safe than sorry. Besides, it's not what you want to use for F7History anyway.)_

**Comment by RH-TLagrone** [comment]
...for the details of my gruesome troubleshooting that led me to this solution, see my commit message body for https://github.com/gui-cs/F7History/pull/20/commits/3b6b0fd2f63e68c2620093d2fe5e574761279f7a

**Comment by tig** [comment]
> P.S. You should also wholly remove the PrivateData.PSData.ExternalModuleDependencies field since it has incompatible semantics with the RequiredModules field. (I'm not sure if actually affects publication/installation behavior in PowerShellGet, but better safe than sorry. Besides, it's not the appropriate field to use given how you've defined F7History's dependencies anyway.)

Hmmm... Removing that makes `Publish-Module -Path $ModulePath -Repository 'local' -ErrorAction Stop` fail in my build script. 

```
Publish-PSArtifactUtility: PowerShellGet cannot resolve the module dependency 'PSReadline' of the module 'F7History' on the repository 'local'. Verify that
the dependent module 'PSReadline' is available in the repository 'local'. If this dependent module 'PSReadline' is managed
externally, add it to the ExternalModuleDependencies entry in the PSData section of the module manifest.
```

**Comment by RH-TLagrone** [comment]
Either you need to pre-download the dependencies from PSGallery and include them in your "Local" repository when publishing F7History to it... or you need a different testing environment architecture that isn't dependent on Local vs. PSGallery repo differences.
